services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    user: '1200:1200'
    ports:
      - 8081:8081
    volumes:
      - './nexus-data:/nexus-data'
      - '/mnt/nexus:/mnt/nexus'
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data/javaprefs
      - TZ=Asia/Seoul
