services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    user: '1200:1200'
    ports:
      - 8081:8081
    volumes:
      - './nexus-data:/nexus-data'
      - '/mnt/nexus:/mnt/nexus'
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g -Djava.util.prefs.userRoot=/nexus-data/javaprefs
    networks:
      - nexus-net

  # Depenency Track - API server
  apiserver:
    image: dependencytrack/apiserver
    container_name: dtrack-api
    restart: unless-stopped
    user: '1200:1200'
    environment:
      # - ALPINE_DATABASE_MODE=internal
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=PASSWORD
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - EXTRA_JAVA_OPTIONS=-Xmx4g

    ports:
      - "8082:8080"
    volumes:
      - './dtrack-data:/data'
    networks:
      - nexus-net

  # Depenency Track - Frontend
  frontend:
    image: dependencytrack/frontend:latest
    container_name: dtract-front
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://192.168.28.10:8082
    ports:
      - "8083:8080"
    depends_on:
      - apiserver
    networks:
      - nexus-net

networks:
  nexus-net:
    driver: bridge
