services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - ALLOW_INTERNAL_REQUESTS=false #optional
    volumes:
      - ./.config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

