services:
  oracle:
    image: gvenzl/oracle-xe:11
    container_name: oracle-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1521:1521"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G

