services:
  agent:
    container_name: pi-agent
    image: zerotymer/agent-isolation:latest-pi
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    networks:
      - agent-net
    volumes:
      - .workspace:/workspace
      - agent-vol:/home/agent/


networks:
  agent-net:
    driver: bridge

volumes:
  agent-vol:
    driver: local
