services:
  dokuwiki:
    container_name: linkding
    image: sissbruecker/linkding:latest-alpine
    ports:
      - 9090:9090
    volumes:
      - '.data:/etc/linkding/data'
    env_file:
      - '.env'
    restart: unless-stopped
