services:
  agent:
    container_name: agents
    image: zerotymer/agent-isolation:latest-full
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    networks:
      - agent-net
    ports:
      - "50022:22"
    volumes:
      - .workspace:/workspace
      - ~/.ssh/id_rsa.pub:/home/agent/.ssh/id_rsa.pub:ro
      - agent-vol:/home/agent/


networks:
  agent-net:
    driver: bridge

volumes:
  agent-vol:
    driver: local
