services:
  runner:
    image: gitea/act_runner:latest
    env_file:
      - .env
    volumes:
      - ./config.yml:/config.yml
      - ./.data:/data
      - /var/run/docker.sock:/var/run/docker.sock
