name: adugard-home

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped

    ports:
      - 53:53/tcp
      - 53:53/udp
      - 30080:80/tcp
      - 30443:443/tcp
      - 30443:443/udp
      - 30784:784/tcp
      - 853:853/tcp
      - 853:853/udp
      - 33000:3000/tcp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 8853:8853/udp

    volumes:
      - adguard-data:/opt/adguardhome

    networks:
      - adguard-net

networks:
  adguard-net:
    driver: bridge

volumes:
  adugard-data:
