services:
  # Depenency Track - API server
  apiserver:
    image: dependencytrack/apiserver
    container_name: dtrack-api
    restart: unless-stopped
    user: '1200:1200'
    environment:
      # - ALPINE_DATABASE_MODE=internal
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://localhost:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=RpYKeDxX7Y
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - EXTRA_JAVA_OPTIONS=-Xmx4g
      - TZ=Asia/Seoul

    ports:
      - "8082:8080"
    volumes:
      - './dtrack-data:/data'
    networks:
      - nexus-net

  # Depenency Track - Frontend
  frontend:
    image: dependencytrack/frontend:latest
    container_name: dtract-front
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://localhost:8082
      - TZ=Asia/Seoul
    ports:
      - "8083:8080"
    depends_on:
      - apiserver
    networks:
      - nexus-net

networks:
  nexus-net:
    driver: bridge
