name: mock
services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/wiremock
    command: ["--global-response-templating"]

