apiVersion: v1
kind: Pod
metadata:
  name: wiremock
  labels: wiremock

spec:
  restartPolicy: Always

  containers:
    - name: wiremock
      image: docker.io/wiremock/wiremock:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumes:
        - name: wiremock-data
          mountPath: /home/wiremock
      args:
        - --global-response-templating

  volumes:
    - name: wiremock-data
      hostPath: 
        path: /srv/wiremock
        type: Directory


