services:
  openclaw-gateway:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw-gateway
    restart: unless-stopped
    ports:
      - "127.0.0.1:18789:18789"
    networks:
      - openclaw_net
    volumes:
      - openclaw_data:/home/node/.openclaw
      - openclaw_workspace:/home/node/.openclaw/workspace
    env_file:
      - default.env
      - path: .env
        required: false
    security_opt:
      - no-new-privileges:true
    shm_size: 2gb
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
    healthcheck:
      test: ["CMD", "node", "dist/docker-healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  openclaw-cli:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw-cli
    profiles:
     - tools
    networks:
     - openclaw_net
    volumes:
      - openclaw_data:/home/node/.openclaw
      - openclaw_workspace:/home/node/.openclaw/workspace
    security_opt:
      - no-new-privileges:true
    entrypoint: ["openclaw"]

networks:
  openclaw_net:
    driver: bridge

volumes:
  openclaw_data:
    driver: local
  openclaw_workspace:
    driver: local
